package dat3.exam.config;

import java.util.List;

public class HotelNameGenerator {

    public static final List<String> HOTEL_NAMES = List.of("Azure Skyline Inn", "Blossom Valley Resort", "Crimson Orchid Suites", "Decadent Spire Retreat", "Eclipse Bay Hotel",
            "Frost Manor", "Gilded Rose Villa", "Harbor Crest Lodge", "Ivory Tower Hotel", "Jewel Garden Estate",
            "Kaleidoscope Palace", "Lunar Springs Inn", "Mystic Pines Resort", "Nebula Oceanfront Hotel", "Opulent River Suites",
            "Pinnacle Summit Lodge", "Quartz Mountain Hotel", "Radiant Shoreline Villa", "Starlight Plaza Hotel", "Twilight Haven Inn",
            "Utopian Dreams Resort", "Velvet Dunes Hotel", "Whispering Willow Suites", "Xanadu Luxury Lodge", "Yellowstone Manor",
            "Zenith Sky Retreat", "Arcadia Boutique Hotel", "Bijou Bliss Inn", "Celestial City Hotel", "Dewdrop Dell Resort",
            "Ethereal Cliffside Inn", "Fantasia Towers", "Grandiose Mirage Hotel", "Haven of Tranquility Suites", "Imperial Skyline Lodge",
            "Jade Serenity Estate", "Kingdom of Dreams Resort", "Lotus Lakefront Inn", "Marvel Vista Hotel", "Nirvana Palace Hotel",
            "Oasis of Elegance Inn", "Pristine Peaks Hotel", "Quaint Quarry Lodge", "Regal Riverscape Inn", "Sapphire Seascape Hotel",
            "Tranquil Tides Resort", "Ultima City Lodge", "Vista Valley Hotel", "Wanderlust Waterfront Suites", "Zephyr Mountain Inn",
            "Ambrosia Orchard Hotel", "Blue Horizon Inn", "Cascading Creek Lodge", "Divine Destiny Suites", "Emerald Enclave Resort",
            "Floral Fantasy Hotel", "Glacier Gateway Inn", "Heritage Harbor Hotel", "Infinity Isle Resort", "Jubilee Gardens Hotel",
            "Knightsbridge Boutique Hotel", "Lakeside Leisure Lodge", "Moonlight Marina Inn", "Nova Nirvana Resort", "Olympus Overlook Hotel",
            "Paradise Pinnacle Suites", "Quartz Reflections Inn", "Riviera Royal Hotel", "Sunset Sanctuary Resort", "Terra Vista Suites",
            "Unwind Utopia Inn", "Violet Valley Hotel", "Wilderness Waves Resort", "Excalibur Estate Inn", "Yellow Daisy Lodge",
            "Zion Zenith Hotel", "Alpha Apex Suites", "Beacon Bluff Inn", "Cosmic Cove Hotel", "Dawn Discovery Resort",
            "Eden Essence Lodge", "Flamingo Flats Hotel", "Grove Garden Inn", "Horizon Heights Hotel", "Iris Island Resort",
            "Jasper Jewel Suites", "Kingsley Keep Hotel", "Luminous Lagoon Lodge", "Majesty Meadows Inn", "Nautical Nook Hotel",
            "Orbit Oasis Inn", "Palm Paradise Hotel", "Quaintwood Quarters Resort", "Rosewood Retreat Hotel", "Serenity Springs Suites",
            "Tropicana Terrace Inn", "Urbanite Utopia Hotel", "Venture Vista Inn", "Waterfront Wharf Hotel", "Xenon Xenith Lodge",
            "Youthful Yacht Hotel", "Zeal Zephyr Inn", "Aurora Arbor Hotel", "Breeze Bluff Suites", "Chateau Charm Inn", "Mirage Mountain Lodge",
            "Opal Oceanview Inn", "Pinecrest Park Hotel", "Quartz Quarry Resort", "Riverside Regal Suites",
            "Sunrise Sanctuary Inn", "Timberline Terrace Hotel", "Urban Oasis Suites", "Vista Valley Lodge", "Whispering Woods Hotel",
            "Xanadu Xpedition Inn", "Yosemite Yard Hotel", "Zestful Zenith Suites", "Azure Archipelago Resort", "Breezy Bluff Manor",
            "Cascade Crest Hotel", "Desert Dunes Inn", "Emerald Edge Lodge", "Fountain Forest Hotel", "Glacier Grove Suites",
            "Haven Hillside Inn", "Ivory Isle Hotel", "Jungle Jewel Lodge", "Kingdom Key Hotel", "Lagoon Landing Suites",
            "Meadow Mist Inn", "Nestled Nook Lodge", "Orchard Oasis Hotel", "Pebble Peak Inn", "Quaint Quiver Resort",
            "Rainforest Ridge Hotel", "Seaside Sunset Inn", "Treetop Terrace Hotel", "Urbane Utopia Suites", "Vineyard Valley Lodge",
            "Wandering Wave Hotel", "Xenial Xanadu Inn", "Yellow Yacht Yard Hotel", "Zenith Zephyr Suites", "Alpine Apex Lodge",
            "Bay Breeze Hotel", "Coral Cove Inn", "Dawnlight Dream Resort", "Enchanted Ember Inn", "Forest Fountain Hotel",
            "Garden Glimpse Lodge", "Harbor Haven Hotel", "Island Ivy Suites", "Journey's Joy Inn", "Knoll Kingdom Lodge",
            "Lakeshore Lullaby Hotel", "Mountain Mystique Inn", "Nirvana Nectar Resort", "Olive Orchard Hotel", "Pearl Pavilion Inn",
            "Quartz Quay Lodge", "Rustic Ridge Hotel", "Skyline Serenity Inn", "Tranquil Tide Hotel", "Urban Uplift Suites",
            "Valley Vista Lodge", "Woodland Whisper Hotel", "Xylia Xyst Inn", "Yarrow Yard Hotel", "Zephyr Zen Lodge",
            "Amber Arch Inn", "Boulder Brook Hotel", "Crimson Crest Inn", "Dewdrop Delight Lodge", "Eclipse Estate Hotel",
            "Floral Fantasy Suites", "Grove Gateway Inn", "Horizon Hacienda Hotel", "Ivy Indulgence Lodge", "Jasper Junction Hotel",
            "Kaleidoscope Keep Inn", "Lily Lagoon Resort", "Majestic Meadow Hotel", "Nova Niche Inn", "Oasis Outlook Lodge",
            "Prism Peak Hotel", "Quaint Quest Inn", "Rainbow Retreat Hotel", "Starlight Summit Inn", "Tropicana Trail Hotel",
            "Utopian Unwind Suites", "Velvet Valley Lodge", "Willow Wind Hotel", "Xanadu Xenith Inn", "Yellowstone Yard Hotel",
            "Zenith Zest Lodge", "Arcadia Atrium Inn", "Blissful Bower Hotel", "Celestial Cove Inn", "Divine Delta Lodge",
            "Eden Enclave Hotel", "Fountain Flair Suites", "Glimmering Grove Inn", "Harmony Haven Hotel", "Iris Island Lodge",
            "Jubilee Junction Hotel", "Kismet Key Inn", "Lavender Landing Resort", "Mystic Mirage Hotel", "Nautical Niche Inn",
            "Olive Orchard Lodge", "Pearl Plaza Hotel", "Quartz Quill Inn", "Radiant Reef Hotel", "Sapphire Shore Inn",
            "Tranquil Terrace Hotel", "Urbanite Utopia Lodge", "Vibrant Vista Hotel", "Wildflower Wind Inn", "Xylia Xanadu Hotel",
            "Yucca Yard Inn", "Zinnia Zenith Lodge", "Aurora Arbor Mansion", "Bamboo Bay Inn", "Canyon Crest Lodge",
            "Dreamland Dunes Hotel", "Elysian Estate Inn", "Fernwood Forest Hotel", "Gardenia Glade Suites", "Haven Heights Inn",
            "Illuminated Isle Hotel", "Jade Jewel Lodge", "Knightsbridge Keep Hotel", "Luminous Lagoon Inn", "Meadow Muse Hotel",
            "Nova Nirvana Lodge", "Oriental Orchard Inn", "Pinecrest Paradise Hotel", "Quaint Quarters Lodge", "Radiance Ridge Hotel",
            "Seabreeze Sanctuary Inn", "Terra Tranquility Hotel", "Utopian Uplift Lodge", "Verdant Valley Hotel", "Wisteria Woods Inn",
            "Xanadu Xylophone Hotel", "Yonder Yard Inn", "Zenith Zest Inn", "Arcadia Arch Inn", "Blossom Bluff Hotel",
            "Cascade Creek Lodge", "Daisy Dell Inn", "Emerald Enclave Hotel", "Fern Fountain Suites", "Glimmering Grove Lodge",
            "Harbor Horizon Hotel", "Ivy Indulgence Inn", "Jasmine Junction Lodge", "Kaleidoscope Keep Hotel", "Lily Lagoon Inn",
            "Mystic Meadow Hotel", "Nirvana Nectar Lodge", "Orchard Oasis Inn", "Pebble Peak Hotel", "Quaint Quiver Inn",
            "Rainforest Ridge Lodge", "Sapphire Seascape Inn", "Tranquil Tide Lodge", "Utopian Unwind Hotel", "Verdant Vista Inn",
            "Willow Wind Lodge", "Xylia Xenith Hotel", "Yarrow Yard Lodge", "Zephyr Zen Inn"
    );

}
